
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='assertize',
    version='0.1.0',
    description='Convert `self.assertSomething(...)` to `assert something`.',
    python_requires='==3.*,>=3.7.0',
    author='Stefane Fermigier',
    author_email='sf@fermigier.com',
    license='GPL',
    entry_points={"console_scripts": ["assertize = assertize:main"]},
    packages=[],
    package_dir={"": "src"},
    package_data={},
    install_requires=['libcst'],
    extras_require={"dev": ["devtools==0.*,>=0.6.1", "pytest==6.*,>=6.2.1"]},
)
