# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="assertize",
    version="0.1.0",
    description="Convert `self.assertSomething(...)` to `assert something`.",
    python_requires="==3.*,>=3.7.0",
    author="Stefane Fermigier",
    author_email="sf@fermigier.com",
    license="GPL",
    entry_points={"console_scripts": ["assertize = assertize:main"]},
    packages=[],
    package_dir={"": "src"},
    package_data={},
    install_requires=["libcst"],
    extras_require={
        "dev": [
            "black",
            "coveralls",
            "devtools==0.*,>=0.6.1",
            "flake8",
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-pytest",
            "flake8-super-call",
            "flake8-tidy-imports",
            "isort",
            "mastool",
            "mccabe",
            "mypy",
            "pre-commit",
            "pytest==6.*,>=6.2.1",
            "pytest-cov",
            "safety",
        ]
    },
)
